#!/bin/bash

IMGDIR=/var/www/img

rrdtool graph $IMGDIR/counter-hour.png -w 1000 -h 300 \
              --title "Gasflow (dt: 5 min)" \
              -s -1h \
              -v "Kubikemeter per uur" \
              DEF:counter='/var/lib/gasmeter/gm-counter.rrd':counter:LAST \
              LINE1:counter#00008B

rrdtool graph $IMGDIR/flow-hour.png -w 1000 -h 300 \
              --title "Gasmeter (dt: 5 min)" \
              -s -1h \
              -v "Gasteller" \
              DEF:flow='/var/lib/gasmeter/gm-flow.rrd':flow:AVERAGE \
              LINE1:flow#00008B

rrdtool graph $IMGDIR/counter-day.png -w 1000 -h 300 \
              --title "Gasflow (dt: 5 min)" \
              -s -1d \
              -v "Kubikemeter per uur" \
              DEF:counter='/var/lib/gasmeter/gm-counter.rrd':counter:LAST \
              LINE1:counter#00008B

rrdtool graph $IMGDIR/flow-day.png -w 1000 -h 300 \
              --title "Gasmeter (dt: 5 min)" \
              -s -1d \
              -v "Gasteller" \
              DEF:flow='/var/lib/gasmeter/gm-flow.rrd':flow:AVERAGE \
              LINE1:flow#00008B
